import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { onest } from "@/font/font";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Realtor AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onest.className} antialiased`}
      >
        <main>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
